---
- name: Disable swap
  ansible.builtin.command: swapoff -a
  register: swapoff
  changed_when: swapoff.rc == 0

- name: Remove swap entry from /etc/fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^\s*([^#\n]+\s+)?swap\s+'
    replace: '# \1swap '
    backup: true

- name: Ensure swap is disabled on boot
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "0"
    state: present
    sysctl_set: true
    reload: true
