---
# - name: Docker setup
#   ansible.builtin.include_tasks: docker-setup.yml

- name: /etc/hosts setup
  ansible.builtin.include_tasks: etc-hosts.yml

- name: Add multipath blacklist
  ansible.builtin.include_tasks: multipath.yml

- name: Update sysctl settings
  ansible.builtin.include_tasks: sysctl.yml
