---
# Refer: https://github.com/bodsch/ansible-snapd/blob/main/tasks/main.yml

- name: Merge snapd configuration between defaults and custom
  ansible.builtin.set_fact:
    snapd_services: "{{ snapd_defaults_services | union(snapd_services) | unique }}"
    snapd_files: "{{ snapd_defaults_files | union(snapd_files) | unique }}"
    snapd_block_packages: "{{ snapd_defaults_block_packages | union(snapd_block_packages) | unique | sort }}"

- name: Remove snap packages
  when:
    - snapd_purge
  block:
    - name: Check installed snaps
      ansible.builtin.command: "snap list"
      register: snap_list_output
      changed_when: false
      failed_when: false

    - name: Snap packages
      ansible.builtin.set_fact:
        snap_list: "{{ snap_list_output.stdout_lines[1:] }}"
      when:
        - snap_list_output.rc == 0

    - name: Uninstall snaps
      ansible.builtin.include_tasks: "uninstall-snaps.yml"
      when:
        - snap_list_output.rc == 0
        - snap_list | length > 0
      loop_control:
        loop_var: snaps_to_remove
      loop:
        "{{ snap_list }}"

- name: Shutdown services, sockets and timers
  ansible.builtin.service:
    name: "{{ item }}"
    state: "{{ snapd_state }}"
    enabled: "{{ snapd_enabled }}"
  failed_when: false
  loop:
    "{{ snapd_services }}"
  loop_control:
    label: "{{ item }}"

- name: Purge all this bullshit
  when:
    - snapd_purge
  block:
    - name: Remove snapd packages
      ansible.builtin.package:
        name: "{{ snapd_block_packages }}"
        state: absent
        purge: true

    - name: Block installation
      when:
        - snapd_block_packages is defined
        - snapd_block_packages | count > 0
      block:
        - name: Block later installations of snapd
          ansible.builtin.template:
            src: apt/preferences.d/snapd.pref.j2
            dest: /etc/apt/preferences.d/snapd.pref
            mode: "0644"
          notify:
            - clean apt cache
            - update package cache
          when:
            - snapd_block_later_installation

    - name: Remove snapd-related directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop: "{{ snapd_files }}"
      loop_control:
        label: "{{ item }}"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
