---
# Refer: https://github.com/bodsch/ansible-snapd/blob/main/tasks/main.yml

- name: Merge snapd configuration between defaults and custom
  ansible.builtin.set_fact:
    host_setup_snapd_services: "{{ host_setup_snapd_defaults_services | union(host_setup_snapd_defaults_services) | unique }}"
    host_setup_snapd_files: "{{ host_setup_snapd_defaults_files | union(host_setup_snapd_files) | unique }}"
    host_setup_snapd_block_packages: "{{ host_setup_snapd_defaults_block_packages | union(host_setup_snapd_block_packages) | unique | sort }}"

- name: Remove snap packages
  when:
    - host_setup_snapd_purge | bool
  block:
    - name: Check installed snaps
      ansible.builtin.command: "snap list"
      register: host_setup_snap_list_output
      changed_when: false
      failed_when: false

    - name: Snap packages
      ansible.builtin.set_fact:
        host_setup_snap_list: "{{ host_setup_snap_list_output.stdout_lines[1:] }}"
      when:
        - host_setup_snap_list_output.rc == 0

    - name: Uninstall snaps
      ansible.builtin.include_tasks: "uninstall-snaps.yml"
      when:
        - host_setup_snap_list_output.rc == 0
        - host_setup_snap_list | length > 0
      loop_control:
        loop_var: snaps_to_remove
      loop: "{{ host_setup_snap_list }}"

- name: Shutdown services, sockets and timers
  ansible.builtin.service:
    name: "{{ item }}"
    state: "{{ host_setup_snapd_state }}"
    enabled: "{{ host_setup_snapd_enabled }}"
  failed_when: false
  loop: "{{ host_setup_snapd_defaults_services }}"
  loop_control:
    label: "{{ item }}"

- name: Purge all this bullshit
  when:
    - host_setup_snapd_purge
  block:
    - name: Remove snapd packages
      ansible.builtin.package:
        name: "{{ host_setup_snapd_block_packages }}"
        state: absent
        purge: true

    - name: Block installation
      when:
        - host_setup_snapd_block_packages is defined
        - host_setup_snapd_block_packages | count > 0
      block:
        - name: Block later installations of snapd
          ansible.builtin.template:
            src: apt/preferences.d/snapd.pref.j2
            dest: /etc/apt/preferences.d/snapd.pref
            mode: "0644"
          notify:
            - clean apt cache
            - update package cache
          when:
            - host_setup_snapd_block_later_installation

    - name: Remove snapd-related directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop: "{{ host_setup_snapd_files }}"
      loop_control:
        label: "{{ item }}"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
