- name: Uninstall snaps
  community.general.snap:
    name: "{{ item | split | first }}"
    state: absent
  failed_when: false
  when: host_setup_snap_list is defined and host_setup_snap_list | length > 0
  loop: "{{ host_setup_snap_list }}"

- name: Check installed snaps
  ansible.builtin.command: "snap list"
  register: host_setup_snap_packages
  changed_when: false

- name: Snap packages
  ansible.builtin.set_fact:
    host_setup_snap_list: "{{ host_setup_snap_packages.stdout_lines[1:] }}"
