# Trivy ignore file (YAML format)
# Reference: https://trivy.dev/docs/latest/configuration/filtering/#trivyignoreyaml
# Note: Misconfiguration IDs use DS- format (not AVD-DS-)

vulnerabilities:
  # Go stdlib vulnerabilities in upstream tools (helm, kubectl, terraform, tflint, trivy)
  # These require upstream maintainers to rebuild with Go 1.24.12+ or 1.25.6+
  - id: CVE-2025-61726
    statement: Go stdlib net/url - no limit on query parameters - waiting for upstream rebuild
  - id: CVE-2025-61728
    statement: Go stdlib archive/zip - excessive CPU consumption - waiting for upstream rebuild
  - id: CVE-2025-61729
    statement: Go stdlib crypto/x509 in tflint - waiting for upstream fix
  - id: CVE-2025-66564
    statement: sigstore/timestamp-authority in tflint/trivy - waiting for upstream fix
  # Alpine transitive dependencies - waiting for base image updates
  - id: CVE-2026-22695
    statement: libpng transitive dependency via graphviz
  - id: CVE-2026-22801
    statement: libpng transitive dependency via graphviz

misconfigurations:
  # Dockerfile checks - acceptable for this use case
  - id: DS-0002
    statement: Image needs root privileges for Ansible/Terraform operations
  - id: DS-0026
    statement: No HEALTHCHECK needed - not a cloud container
  - id: DS-0011
    statement: Ansible Jinja2 template - Trivy misparses role_name as COPY args
