# Trivy ignore file (YAML format)
# Reference: https://trivy.dev/docs/latest/configuration/filtering/#trivyignoreyaml
# Note: Misconfiguration IDs use DS- format (not AVD-DS-)

vulnerabilities:
  # Go stdlib vulnerabilities in upstream tools (helm, kubectl, terraform, tflint, trivy)
  # These require upstream maintainers to rebuild with Go 1.24.12+ or 1.25.6+
  - id: CVE-2025-61726
    statement: Go stdlib net/url - no limit on query parameters - waiting for upstream rebuild
  - id: CVE-2025-61728
    statement: Go stdlib archive/zip - excessive CPU consumption - waiting for upstream rebuild
  - id: CVE-2025-61729
    statement: Go stdlib crypto/x509 in tflint - waiting for upstream fix
  - id: CVE-2025-66564
    statement: sigstore/timestamp-authority in tflint/trivy - waiting for upstream fix
  # Go stdlib crypto/tls vulnerabilities in all upstream Go binaries
  # (helm, kubectl, terraform, task, tflint, trivy)
  # CRITICAL: Requires Go >= 1.25.7 - no upstream tool has been rebuilt yet as of 2026-02-20
  # Reference: https://security.snyk.io/vuln/SNYK-GOLANG-STDCRYPTOTLS-15238826
  # EPSS: 0.01% (2nd percentile) - CI tooling container not exposed to untrusted TLS clients
  - id: CVE-2025-68121
    statement: Go stdlib crypto/tls session resumption - waiting for upstream rebuild with Go 1.25.7+
  # HIGH: Requires Go >= 1.25.6 - fixed in trivy v0.69.1, other tools still pending upstream rebuild
  # Reference: https://avd.aquasec.com/nvd/cve-2025-61730
  - id: CVE-2025-61730
    statement: Go stdlib crypto/tls TLS 1.3 handshake - waiting for upstream rebuild with Go 1.25.6+
  # Alpine transitive dependencies - waiting for base image updates
  - id: CVE-2026-22695
    statement: libpng transitive dependency via graphviz
  - id: CVE-2026-22801
    statement: libpng transitive dependency via graphviz

misconfigurations:
  # Dockerfile checks - acceptable for this use case
  - id: DS-0002
    statement: Image needs root privileges for Ansible/Terraform operations
  - id: DS-0026
    statement: No HEALTHCHECK needed - not a cloud container
  - id: DS-0011
    statement: Ansible Jinja2 template - Trivy misparses role_name as COPY args
