version: "3"

dotenv: [".env"]

tasks:
  repo:setup:mac:
    cmds:
      - ./scripts/repo-setup.sh

  repo:setup:
    cmds:
      - pre-commit autoupdate
      - ansible-galaxy install -r stage1/requirements.yml
      - pip install --no-cache-dir -r stage1/requirements-pip.txt

  precommit:
    cmds:
      - pre-commit run --all-files

  docker:build:
    cmds:
      - ./scripts/docker-build.sh

  docker:run:
    cmds:
      - ./scripts/docker-run.sh

  docker:exec:
    cmds:
      - task: docker:run
      - docker exec -it "homelab-infrastructure" /bin/bash

  docker:trivy:
    desc: Build and scan container image for vulnerabilities (matches CI workflow)
    cmds:
      # Build image with --no-cache to match CI workflow behavior
      # Per docker/build-push-action: https://github.com/docker/build-push-action#inputs
      - ./scripts/docker-build.sh --no-cache
      # Scan with Trivy matching container-security.yml workflow
      # Per Trivy CLI docs: https://trivy.dev/docs/latest/references/configuration/cli/trivy_image/
      - trivy image
        --config trivy.yaml
        --ignorefile .trivyignore.yaml
        --severity CRITICAL,HIGH
        --exit-code 1
        chrisleekr/homelab-infrastructure:latest

  stage1:ansible:ping:
    desc: Verify access to the cluster
    dir: stage1
    cmds:
      - ansible all -i "inventories/inventory.yml" -m ping

  stage1:ansible:playbook:
    desc: Deploy complete server setup and Kubernetes cluster
    dir: stage1
    cmds:
      - ansible-playbook --ask-become-pass -i "inventories/inventory.yml" site.yml

  stage2:terraform:init:
    desc: Initialize Terraform
    dir: stage2
    cmds:
      - terraform init
      - terraform workspace select homelab-k8s

  stage2:terraform:init:upgrade:
    desc: Upgrade Terraform providers to latest versions satisfying constraints. Run in root and all child modules.
    cmds:
      - cd stage2 && terraform init -upgrade
      - |
        for dir in stage2/*/; do
          if [ -f "${dir}provider.tf" ]; then
            echo "Upgrading providers in ${dir}..."
            (cd "${dir}" && terraform init -upgrade -backend=false)
          fi
        done

  stage2:terraform:init:lock:
    desc: Regenerate all provider lock files with multi-platform hashes. Run inside Docker container
    cmds:
      # Remove darwin-built provider caches from child modules — they cannot be used inside linux_amd64 Docker container.
      # Per HashiCorp Discuss: https://discuss.hashicorp.com/t/trying-to-run-terraform-validate-with-tf-plugin-cache-dir-set/64632
      - find stage2 -mindepth 2 -maxdepth 2 -name ".terraform" -type d -exec rm -rf {} +
      # Lock root module (darwin_arm64 + linux_amd64 so both macOS and Docker CI work)
      # Per HashiCorp docs: https://developer.hashicorp.com/terraform/cli/commands/providers/lock
      - cd stage2 && terraform providers lock -platform=darwin_arm64 -platform=linux_amd64
      # Lock each child module that declares its own providers.
      # terraform init -upgrade is required first to resolve any stale lock file versions
      # that no longer satisfy current version constraints in provider.tf.
      # Ref: https://developer.hashicorp.com/terraform/cli/commands/init#upgrade
      - |
        for dir in stage2/*/; do
          if [ -f "${dir}provider.tf" ]; then
            echo "Locking providers in ${dir}..."
            (cd "${dir}" && terraform providers lock -platform=darwin_arm64 -platform=linux_amd64)
          fi
        done

  stage2:terraform:plan:
    desc: Plan the Terraform deployment
    dir: stage2
    cmds:
      - terraform plan

  stage2:terraform:refresh:
    desc: Refresh Terraform state to match real infrastructure
    dir: stage2
    cmds:
      - terraform refresh

  stage2:terraform:apply:
    desc: Apply the Terraform deployment
    dir: stage2
    cmds:
      - terraform apply
