---
- name: Check whether kubectl is installed on control node
  ansible.builtin.command: "kubectl"
  register: kubectl_installed
  ignore_errors: true
  delegate_to: 127.0.0.1
  become: false
  changed_when: false

- name: Apply K3S kubeconfig to control node
  when: kubectl_installed.rc == 0
  block:
    - name: Get 8443 port number
      ansible.builtin.shell:
        cmd: |
          set -o pipefail && \
          docker inspect minikube | jq -r '.[0].NetworkSettings.Ports."8443/tcp".[0].HostPort'
        executable: /bin/bash
      register: port_number
      changed_when: port_number.rc != 0

    - name: Generate kubeconfig
      ansible.builtin.shell: |
        export KUBECONFIG=/tmp/kubeconfig.aws
        kubectl config set-cluster minikube --embed-certs \
          --certificate-authority=/root/.minikube/ca.crt \
          --server=https://{{ ansible_host }}:{{ port_number.stdout }}
        kubectl config set-credentials minikube \
          --embed-certs --client-certificate=/root/.minikube/profiles/minikube/client.crt \
          --client-key=/root/.minikube/profiles/minikube/client.key
        kubectl config set-context minikube --cluster=minikube --user=minikube
        kubectl config use-context minikube
        export KUBECONFIG=~/.kube/config
      register: generate_kubeconfig
      changed_when: generate_kubeconfig.rc != 0

    - name: Copy kubeconfig to localhost
      ansible.builtin.fetch:
        src: /tmp/kubeconfig.aws
        dest: "{{ kubeconfig }}"
        flat: true
