---
# https://medium.com/@areesmoon/setting-up-minikube-and-accessing-minikube-dashboard-09b42fa25fb6

# Reference: https://stackoverflow.com/a/77917988
- name: Remove Temp Files
  ansible.builtin.command: "rm -rf /tmp/juju-*"
  register: minikube_server_remove_temp_files
  changed_when: minikube_server_remove_temp_files.rc == 0

# Reference: https://github.com/climacs-net/my-cool-service/blob/c1dd14e23aa54c1cdfaf0e85f9540a8631a1b1d8/ansible/playbook.yml#L83C1-L84C48
- name: Fix permissions for Minikube
  ansible.posix.sysctl:
    name: fs.protected_regular
    value: "0"
    state: present
    reload: true

- name: Make sysctl setting permanent
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/99-custom.conf
    line: "fs.protected_regular = 0"
    create: true
    mode: "0600"
  notify: "reload sysctl"

- name: Create minikube.service file
  ansible.builtin.template:
    src: minikube.service.j2
    dest: /usr/lib/systemd/system/minikube.service
    owner: root
    group: root
    mode: "u=rw,go=r"
  register: minikube_server_minikube_service

- name: Create minitunnel.service file
  ansible.builtin.template:
    src: minitunnel.service.j2
    dest: /usr/lib/systemd/system/minitunnel.service
    owner: root
    group: root
    mode: "u=rw,go=r"
  register: minikube_server_minitunnel_service

- name: Notify handlers
  when: minikube_server_minikube_service.changed or minikube_server_minitunnel_service.changed
  ansible.builtin.debug:
    msg: "Reloading systemd daemon and enable services"
  changed_when: true
  notify:
    - "reload systemd daemon"
    - "enable minikube"
    - "enable minitunnel"

# Check if minikube service is running
- name: Check minikube service status
  ansible.builtin.systemd_service:
    name: minikube
    state: started
  register: minikube_server_minikube_status
  failed_when: false
  changed_when: false

# Notify to start minikube if it's not running
- name: Notify to start minikube if not running
  when: minikube_server_minikube_status.status is not defined or minikube_server_minikube_status.status.ActiveState != 'active'
  ansible.builtin.debug:
    msg: "Minikube service is not running, notifying to start it."
  notify: "start minikube"

# Check if minikube service is running
- name: Check minitunnel service status
  ansible.builtin.systemd_service:
    name: minitunnel
    state: started
  register: minikube_server_minitunnel_status
  failed_when: false
  changed_when: false

# Notify to start minitunnel if it's not running
- name: Notify to start minitunnel if not running
  when: minikube_server_minitunnel_status.status is not defined or minikube_server_minitunnel_status.status.ActiveState != 'active'
  ansible.builtin.debug:
    msg: "Minitunnel service is not running, notifying to start it."
  notify: "start minitunnel"

# If /usr/local/bin/kubectl does not exist, create a symlink to minikube
- name: Check if /usr/local/bin/kubectl exists
  ansible.builtin.stat:
    path: /usr/local/bin/kubectl
  register: minikube_server_kubectl_stat

- name: Set kubectl alias
  ansible.builtin.shell:
    cmd: "ln -s $(which minikube) /usr/local/bin/kubectl"
  register: minikube_server_kubectl_alias
  changed_when: minikube_server_kubectl_alias.rc == 0
  when: not minikube_server_kubectl_stat.stat.exists

# One more time
# Reference: https://stackoverflow.com/a/77917988
- name: Remove Temp Files
  ansible.builtin.command: "rm -rf /tmp/juju-*"
  register: minikube_server_remove_temp_files_again
  changed_when: minikube_server_remove_temp_files_again.rc == 0

# Reference: https://github.com/climacs-net/my-cool-service/blob/c1dd14e23aa54c1cdfaf0e85f9540a8631a1b1d8/ansible/playbook.yml#L83C1-L84C48
- name: Fix permissions for Minikube
  ansible.posix.sysctl:
    name: fs.protected_regular
    value: "0"
    state: present
    reload: true

- name: Run kubectl cluster-info
  ansible.builtin.command: "kubectl cluster-info"
  register: minikube_server_kubectl_cluster_info
  changed_when: minikube_server_kubectl_cluster_info.rc == 0
