---
# /usr/local/bin/containerd --version
# containerd github.com/containerd/containerd/v2 v2.1.4 75cb2b7193e4e490e9fbdc236c0e811ccaba3376

- name: Get containerd installed version
  ansible.builtin.command: /usr/local/bin/containerd --version
  register: kubeadm_server_containerd_version_output
  changed_when: false
  ignore_errors: true

# - name: Debug containerd installed version
#   ansible.builtin.debug:
#     msg: |
#       Containerd version output: {{ kubeadm_server_containerd_version_output.stdout }}
#       Containerd version output lines: {{ kubeadm_server_containerd_version_output.stdout_lines }}
#       Containerd version output stderr lines: {{ kubeadm_server_containerd_version_output.stderr_lines }}
#       Containerd version output stderr: {{ kubeadm_server_containerd_version_output.stderr }}
#       Containerd version output rc: {{ kubeadm_server_containerd_version_output.rc }}

- name: Set containerd installed version
  when:
    - kubeadm_server_containerd_version_output.rc == 0
    - kubeadm_server_containerd_version_output.stdout_lines | length > 0
  ansible.builtin.set_fact:
    kubeadm_server_containerd_installed_version: "{{ kubeadm_server_containerd_version_output.stdout_lines[0] | regex_replace('^containerd .* v([0-9.]+).*$', '\\1') }}"

- name: Debug containerd installed version
  ansible.builtin.debug:
    msg: "Containerd installed version: {{ kubeadm_server_containerd_installed_version }}"

- name: Display containerd version information
  ansible.builtin.debug:
    msg: |
      Current containerd version: {{ kubeadm_server_containerd_installed_version | default('Not installed') }}
      Target containerd version: {{ containerd_version }}
      Upgrade needed: {{ (kubeadm_server_containerd_installed_version is defined and kubeadm_server_containerd_installed_version is version(containerd_version, '<')) | default(true) }}

- name: Install containerd
  when: >
    'containerd.service' not in ansible_facts.services or ansible_facts.services['containerd.service'].state != 'running' or
    (kubeadm_server_containerd_version_output.rc != 0) or
    (kubeadm_server_containerd_installed_version is defined and kubeadm_server_containerd_installed_version is version(containerd_version, '<'))
  block:
    - name: Download containerd tarball
      vars:
        base_url: "https://github.com/containerd/containerd/releases/download"
        path: "containerd-{{ containerd_version }}-linux-{{ host_machine_architecture }}.tar.gz"
      ansible.builtin.get_url:
        url: "{{ base_url }}/v{{ containerd_version }}/{{ path }}"
        dest: "/tmp/{{ path }}"
        mode: "0644"
        force: true

    - name: Extract containerd tarball to /usr/local
      ansible.builtin.unarchive:
        src: "/tmp/containerd-{{ containerd_version }}-linux-{{ host_machine_architecture }}.tar.gz"
        dest: /usr/local
        remote_src: true

    - name: Download containerd.service file
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/containerd/containerd/main/containerd.service
        dest: /lib/systemd/system/containerd.service
        mode: "0644"

    - name: Reload systemd daemon and enable containerd service
      ansible.builtin.systemd:
        daemon_reload: true
        enabled: true
        state: started
        name: containerd

    - name: Create /etc/containerd directory if it doesn't exist already.
      ansible.builtin.file:
        path: /etc/containerd/
        state: directory
        mode: "0644"

    - name: Generate default config for containerd and save it to config.toml file.
      ansible.builtin.shell: "containerd config default > /etc/containerd/config.toml"
      register: kubeadm_server_containerd_toml
      changed_when: kubeadm_server_containerd_toml.rc != 0 and kubeadm_server_containerd_toml.stdout != ""

    - name: Update the value of SystemdCgroup in the config.toml file.
      ansible.builtin.replace:
        path: /etc/containerd/config.toml
        regexp: "SystemdCgroup = false"
        replace: "SystemdCgroup = true"

    - name: Restart containerd service
      ansible.builtin.service:
        name: containerd
        state: restarted
