---
- name: Ensure kubeconfig is created
  vars:
    users:
      - { user: "root", home_dir: "/root" }
  block:
    - name: Check if kubeconfig is already created
      ansible.builtin.stat:
        path: "{{ item.home_dir }}/.kube/config"
      register: kubeadm_server_kubeconfig_check
      loop: "{{ users }}"

    - name: Create .kube directory
      ansible.builtin.file:
        path: "{{ item.home_dir }}/.kube"
        state: directory
        mode: "0750"
        owner: "{{ item.user }}"
        group: "{{ item.user }}"
      loop: "{{ users }}"
      when: not kubeadm_server_kubeconfig_check.results[item | int].stat.exists

    - name: Copy admin.conf to user's kube config
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ item.home_dir }}/.kube/config"
        remote_src: true
        mode: "0600"
        owner: "{{ item.user }}"
        group: "{{ item.user }}"
      loop: "{{ users }}"
      when: not kubeadm_server_kubeconfig_check.results[item | int].stat.exists
