---
- name: Check if crictl exists
  ansible.builtin.stat:
    path: /usr/local/bin/crictl
  register: crictl_stat

- name: Download and extract crictl
  when: not crictl_stat.stat.exists
  block:
    - name: Download crictl
      vars:
        base_url: "https://github.com/kubernetes-sigs/cri-tools/releases/download"
        path: "crictl-v{{ crictl_version }}-linux-{{ host_machine_architecture }}.tar.gz"
      ansible.builtin.get_url:
        url: "{{ base_url }}/v{{ crictl_version }}/{{ path }}"
        dest: /tmp/crictl.tar.gz
        mode: "0644"

    - name: Extract crictl
      ansible.builtin.unarchive:
        src: /tmp/crictl.tar.gz
        dest: /usr/local/bin/
        remote_src: true
