---
- name: Check if CNI exists
  ansible.builtin.stat:
    path: /opt/cni/bin/macvlan
  register: kubeadm_server_cni_file

- name: Install CNI
  when: not kubeadm_server_cni_file.stat.exists
  block:
    - name: Download CNI plugins
      vars:
        base_url: "https://github.com/containernetworking/plugins/releases/download"
        path: "cni-plugins-linux-{{ host_machine_architecture }}-v{{ cni_version }}.tgz"
      ansible.builtin.get_url:
        url: "{{ base_url }}/v{{ cni_version }}/{{ path }}"
        dest: "/tmp/{{ path }}"
        mode: "0644"

    - name: Ensure CNI bin directory exists
      ansible.builtin.file:
        path: /opt/cni/bin
        state: directory
        mode: "0644"

    - name: Extract CNI plugins to bin directory
      ansible.builtin.unarchive:
        src: "/tmp/cni-plugins-linux-{{ host_machine_architecture }}-v{{ cni_version }}.tgz"
        dest: /opt/cni/bin/
        remote_src: true
