---
- name: Check if runc exists
  ansible.builtin.stat:
    path: /usr/local/sbin/runc
  register: kubeadm_server_runc_file

# $ runc --version
# runc version 1.1.13
# commit: v1.1.13-0-g58aa9203-dirty
# spec: 1.0.2-dev
# go: go1.21.11
# libseccomp: 2.5.5

- name: Get runc installed version
  ansible.builtin.command: /usr/local/sbin/runc --version
  register: kubeadm_server_runc_version_output
  changed_when: false
  ignore_errors: true

- name: Set runc installed version
  when:
    - kubeadm_server_runc_version_output.rc == 0
    - kubeadm_server_runc_version_output.stdout_lines | length > 0
  ansible.builtin.set_fact:
    kubeadm_server_runc_installed_version: "{{ kubeadm_server_runc_version_output.stdout_lines[0] | regex_replace('^runc version\\s+([0-9.]+).*$', '\\1') }}"

- name: Debug runc installed version
  ansible.builtin.debug:
    msg: "Runc installed version: {{ kubeadm_server_runc_installed_version }}"

- name: Display runc version information
  ansible.builtin.debug:
    msg: |
      Current runc version: {{ kubeadm_server_runc_installed_version | default('Not installed') }}
      Target runc version: {{ runc_version }}
      Upgrade needed: {{ (kubeadm_server_runc_installed_version is defined and kubeadm_server_runc_installed_version is version(runc_version, '<')) | default(true) }}

- name: Install or upgrade runc
  when: >
    not kubeadm_server_runc_file.stat.exists or
    (kubeadm_server_runc_version_output.rc != 0) or
    (kubeadm_server_runc_installed_version is defined and kubeadm_server_runc_installed_version is version(runc_version, '<'))
  block:
    - name: Download runc
      ansible.builtin.get_url:
        url: "https://github.com/opencontainers/runc/releases/download/v{{ runc_version }}/runc.{{ host_machine_architecture }}"
        dest: /usr/local/sbin/runc
        mode: "0755"
        force: true

    - name: Verify runc version after download
      ansible.builtin.command: /usr/local/sbin/runc --version
      register: kubeadm_server_runc_post_download_version
      changed_when: false

    - name: Display runc post download version
      ansible.builtin.debug:
        msg: "{{ kubeadm_server_runc_post_download_version.stdout }}"

    - name: Display downloaded runc version
      ansible.builtin.debug:
        msg: "Downloaded runc version: {{ (kubeadm_server_runc_post_download_version.stdout | regex_replace('^runc version (.*)$', '\\1')) }}"
