---
- name: Enable minikube service
  listen: "enable minikube"
  ansible.builtin.systemd_service:
    name: minikube
    enabled: true

- name: Start minikube service
  listen: "start minikube"
  ansible.builtin.systemd_service:
    name: minikube
    state: started

- name: Enable minitunnel service
  listen: "enable minitunnel"
  ansible.builtin.systemd_service:
    name: minitunnel
    enabled: true

- name: Start minitunnel service
  listen: "start minitunnel"
  ansible.builtin.systemd_service:
    name: minitunnel
    state: started
