---
- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
  become: true

- name: Create jail.local configuration for SSH
  ansible.builtin.blockinfile:
    path: /etc/fail2ban/jail.local
    mode: "0644"
    create: true
    block: |
      [sshd]
      enabled = true
      port = {{ sshd_port }}
      filter = sshd
      logpath = /var/log/auth.log
      maxretry = 5
  become: true
  notify: Restart fail2ban service
