---
- name: Rename kubeconfig
  ansible.builtin.import_tasks: rename-kubeconfig.yml

- name: Install Kubernetes components
  when: kubernetes_cluster_type == 'kubeadm'
  block:
    - name: Install MetalLB
      ansible.builtin.include_tasks: install-metallb.yml

    - name: Install metrics-server
      ansible.builtin.include_tasks: install-metrics-server.yml
