---
- name: Rename ~/.kube/config.new to ~/.kube/config locally
  ansible.builtin.command:
    cmd: mv ~/.kube/config.new ~/.kube/config
  register: localhost_post_setup_mv_output
  changed_when: localhost_post_setup_mv_output.rc != 0

- name: Use kube context to the cluster
  ansible.builtin.shell: kubectl config use-context $(kubectl config get-contexts -o name)
  register: localhost_post_setup_kubectl_output
  changed_when: localhost_post_setup_kubectl_output.rc != 0
